#!/bin/bash

set -e

source ./utils

status "Query GitHub API to get the latest stable tag"
LATEST_TAG=$(latestTag)
IMAGE_TAG=conda-"$LATEST_TAG"
msg ${IMAGE_TAG:-"Not found"}

if [[ -n "${LATEST_TAG}" ]]; then
    status "Update Dockerfile with the latest stable tag"
    sed "s|ENV\s*IMAGE_NUCLIDE_VERSION=.*|ENV IMAGE_NUCLIDE_VERSION=$lATEST_TAG \\\|g" -i Dockerfile
    msg OK

    status "Build image $IMAGE_NAME:$IMAGE_TAG"
    docker build . --tag $IMAGE_NAME:$IMAGE_TAG
    msg OK

    status "Tag image $IMAGE_NAME:latest from $IMAGE_NAME:$IMAGE_TAG"
    docker tag $IMAGE_NAME:$IMAGE_TAG $IMAGE_NAME:conda-latest
    msg OK
else
    status "Build failed"
    msg Latest stable tag not found
    exit 1
fi
