#!/bin/bash

set -e

source ./utils

status "Query GitHub API to get the latest stable tag"
IMAGE_TAG="conda"-$(latestTag)
msg $IMAGE_TAG

status "Login DockerHub"
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
msg OK

status "Pushing $IMAGE_NAME:$IMAGE_TAG"
docker push $IMAGE_NAME:$IMAGE_TAG
msg OK

status "Pushing $IMAGE_NAME:conda-latest"
docker push $IMAGE_NAME:conda-latest
msg OK
